.\" Manpage for hosting.
.TH man 8 "01 Oct 2019" "1.0" "hosting man page"
.SH NAME
hosting \- create a new multi-tenant hosting account
.SH SYNOPSIS
hosting [add|del] <username> <domain> [<domain>]
.SH DESCRIPTION
Hosting is a multi-tenant hosting management script. It supports users, static content, PHP, Node and Docker back-ends.
.SH OPTIONS
The nuseradd does not take any options. However, you can supply username.
.SH SEE ALSO
useradd(8), nginx(8), docker(1)
.SH BUGS
Probably lots. Please report them to the author.
.SH AUTHOR
Mark Griffin <mark.griffin@linux.com>